// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxFoLqDVo3pykmC2MNRIKr592MyTUYVbM',
    appId: '1:1051741114316:web:0211d343b585fae4b45769',
    messagingSenderId: '1051741114316',
    projectId: 'notesapp-deb81',
    authDomain: 'notesapp-deb81.firebaseapp.com',
    storageBucket: 'notesapp-deb81.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAykXuok50Pf-c_EokAXKg0KwW4Yo4SOKw',
    appId: '1:1051741114316:android:721e3e7a1af33a3fb45769',
    messagingSenderId: '1051741114316',
    projectId: 'notesapp-deb81',
    storageBucket: 'notesapp-deb81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1jkV1ukP1vmfPtzr5VVYJH1yNMiF52MM',
    appId: '1:1051741114316:ios:4e20c21fc3c4fcd2b45769',
    messagingSenderId: '1051741114316',
    projectId: 'notesapp-deb81',
    storageBucket: 'notesapp-deb81.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1jkV1ukP1vmfPtzr5VVYJH1yNMiF52MM',
    appId: '1:1051741114316:ios:4e20c21fc3c4fcd2b45769',
    messagingSenderId: '1051741114316',
    projectId: 'notesapp-deb81',
    storageBucket: 'notesapp-deb81.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxFoLqDVo3pykmC2MNRIKr592MyTUYVbM',
    appId: '1:1051741114316:web:d1faea945ac14b2bb45769',
    messagingSenderId: '1051741114316',
    projectId: 'notesapp-deb81',
    authDomain: 'notesapp-deb81.firebaseapp.com',
    storageBucket: 'notesapp-deb81.firebasestorage.app',
  );
}
